name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs'
      - mkdocs.yml
  # schedule:
  #   - cron: "0 15 * * 1"

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    env:
      OUT: site
    steps:
      - uses: actions/checkout@v4
        # with:
        #   submodule: "recursive"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      # - run: pip install -r requirements.txt
      - name: Build Data
        run: bash deploy2.sh ${{ env.OUT }}
      - name: Setup pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUT }}
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
